/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddApplianceRequest {
  'name' : string,
  'installDate' : bigint,
  'lastServiceDate' : bigint,
  'category' : Category,
  'brand' : string,
}
export interface AddMaintenanceTaskRequest {
  'status' : Status,
  'title' : string,
  'dueDate' : bigint,
  'description' : string,
  'priority' : Priority,
  'applianceId' : [] | [bigint],
}
export interface Alert {
  'id' : bigint,
  'alertType' : AlertType,
  'createdAt' : bigint,
  'message' : string,
}
export type AlertType = { 'warning' : null } |
  { 'info' : null } |
  { 'critical' : null };
export interface Appliance {
  'id' : bigint,
  'name' : string,
  'installDate' : bigint,
  'lastServiceDate' : bigint,
  'category' : Category,
  'brand' : string,
  'healthScore' : bigint,
}
export type ApplianceId = bigint;
export interface ApplianceSummary {
  'totalAppliances' : bigint,
  'oldestAppliance' : [] | [Appliance],
  'averageHealthScore' : bigint,
  'mostServicedAppliance' : [] | [Appliance],
}
export type Category = { 'other' : null } |
  { 'hvac' : null } |
  { 'plumbing' : null } |
  { 'kitchen' : null } |
  { 'electrical' : null } |
  { 'laundry' : null };
export interface DashboardStats {
  'homeHealthScore' : bigint,
  'activeAlerts' : bigint,
  'upcomingTasks' : bigint,
}
export interface MaintenanceSummary {
  'overdueTasks' : bigint,
  'totalTasks' : bigint,
  'completedTasks' : bigint,
  'upcomingTasks' : bigint,
}
export interface MaintenanceTask {
  'id' : bigint,
  'status' : Status,
  'title' : string,
  'dueDate' : bigint,
  'description' : string,
  'priority' : Priority,
  'applianceId' : bigint,
}
export type Priority = { 'low' : null } |
  { 'high' : null } |
  { 'critical' : null } |
  { 'medium' : null };
export type Status = { 'pending' : null } |
  { 'completed' : null } |
  { 'overdue' : null } |
  { 'inProgress' : null };
export type TaskId = bigint;
export interface UpdateApplianceRequest {
  'name' : string,
  'installDate' : bigint,
  'lastServiceDate' : bigint,
  'category' : Category,
  'brand' : string,
}
export interface UpdateMaintenanceTaskRequest {
  'status' : Status,
  'title' : string,
  'dueDate' : bigint,
  'description' : string,
  'priority' : Priority,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAlert' : ActorMethod<[string, AlertType], undefined>,
  'addAppliance' : ActorMethod<[AddApplianceRequest], ApplianceId>,
  'addMaintenanceTask' : ActorMethod<[AddMaintenanceTaskRequest], TaskId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeTask' : ActorMethod<[bigint], undefined>,
  'deleteAlert' : ActorMethod<[bigint], undefined>,
  'deleteAppliance' : ActorMethod<[bigint], undefined>,
  'deleteMaintenanceTask' : ActorMethod<[bigint], undefined>,
  'getActiveAlertsCount' : ActorMethod<[], bigint>,
  'getAlertById' : ActorMethod<[bigint], Alert>,
  'getAlerts' : ActorMethod<[], Array<Alert>>,
  'getAlertsByDateRange' : ActorMethod<[bigint, bigint], Array<Alert>>,
  'getAlertsSortedBySeverity' : ActorMethod<[], Array<Alert>>,
  'getApplianceById' : ActorMethod<[bigint], Appliance>,
  'getApplianceSummary' : ActorMethod<[], ApplianceSummary>,
  'getAppliances' : ActorMethod<[], Array<Appliance>>,
  'getAppliancesByCategory' : ActorMethod<[Category], Array<Appliance>>,
  'getAppliancesSortedByHealthScore' : ActorMethod<[], Array<Appliance>>,
  'getAppliancesSortedByName' : ActorMethod<[], Array<Appliance>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCriticalAlerts' : ActorMethod<[], Array<Alert>>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getMaintenanceSummary' : ActorMethod<[], MaintenanceSummary>,
  'getMaintenanceTasks' : ActorMethod<[], Array<MaintenanceTask>>,
  'getOverdueTasks' : ActorMethod<[], Array<MaintenanceTask>>,
  'getPendingTasks' : ActorMethod<[], Array<MaintenanceTask>>,
  'getSortedUpcomingTasks' : ActorMethod<[], Array<MaintenanceTask>>,
  'getTaskById' : ActorMethod<[bigint], MaintenanceTask>,
  'getTasksByPriority' : ActorMethod<[Priority], Array<MaintenanceTask>>,
  'getTasksByStatus' : ActorMethod<[Status], Array<MaintenanceTask>>,
  'getTasksForAppliance' : ActorMethod<[bigint], Array<MaintenanceTask>>,
  'getTasksWithDueDateBetweenRange' : ActorMethod<
    [bigint, bigint],
    Array<MaintenanceTask>
  >,
  'getUpcomingTasks' : ActorMethod<[], Array<MaintenanceTask>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'insertTestData' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'resetUserData' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateAppliance' : ActorMethod<[bigint, UpdateApplianceRequest], undefined>,
  'updateApplianceHealthScores' : ActorMethod<[], undefined>,
  'updateMaintenanceTask' : ActorMethod<
    [bigint, UpdateMaintenanceTaskRequest],
    undefined
  >,
  'updateTaskStatuses' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];