/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AlertType = IDL.Variant({
  'warning' : IDL.Null,
  'info' : IDL.Null,
  'critical' : IDL.Null,
});
export const Category = IDL.Variant({
  'other' : IDL.Null,
  'hvac' : IDL.Null,
  'plumbing' : IDL.Null,
  'kitchen' : IDL.Null,
  'electrical' : IDL.Null,
  'laundry' : IDL.Null,
});
export const AddApplianceRequest = IDL.Record({
  'name' : IDL.Text,
  'installDate' : IDL.Int,
  'lastServiceDate' : IDL.Int,
  'category' : Category,
  'brand' : IDL.Text,
});
export const ApplianceId = IDL.Nat;
export const Status = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'overdue' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Priority = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'critical' : IDL.Null,
  'medium' : IDL.Null,
});
export const AddMaintenanceTaskRequest = IDL.Record({
  'status' : Status,
  'title' : IDL.Text,
  'dueDate' : IDL.Int,
  'description' : IDL.Text,
  'priority' : Priority,
  'applianceId' : IDL.Opt(IDL.Nat),
});
export const TaskId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Alert = IDL.Record({
  'id' : IDL.Nat,
  'alertType' : AlertType,
  'createdAt' : IDL.Int,
  'message' : IDL.Text,
});
export const Appliance = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'installDate' : IDL.Int,
  'lastServiceDate' : IDL.Int,
  'category' : Category,
  'brand' : IDL.Text,
  'healthScore' : IDL.Int,
});
export const ApplianceSummary = IDL.Record({
  'totalAppliances' : IDL.Nat,
  'oldestAppliance' : IDL.Opt(Appliance),
  'averageHealthScore' : IDL.Int,
  'mostServicedAppliance' : IDL.Opt(Appliance),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DashboardStats = IDL.Record({
  'homeHealthScore' : IDL.Int,
  'activeAlerts' : IDL.Nat,
  'upcomingTasks' : IDL.Nat,
});
export const MaintenanceSummary = IDL.Record({
  'overdueTasks' : IDL.Nat,
  'totalTasks' : IDL.Nat,
  'completedTasks' : IDL.Nat,
  'upcomingTasks' : IDL.Nat,
});
export const MaintenanceTask = IDL.Record({
  'id' : IDL.Nat,
  'status' : Status,
  'title' : IDL.Text,
  'dueDate' : IDL.Int,
  'description' : IDL.Text,
  'priority' : Priority,
  'applianceId' : IDL.Nat,
});
export const UpdateApplianceRequest = IDL.Record({
  'name' : IDL.Text,
  'installDate' : IDL.Int,
  'lastServiceDate' : IDL.Int,
  'category' : Category,
  'brand' : IDL.Text,
});
export const UpdateMaintenanceTaskRequest = IDL.Record({
  'status' : Status,
  'title' : IDL.Text,
  'dueDate' : IDL.Int,
  'description' : IDL.Text,
  'priority' : Priority,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAlert' : IDL.Func([IDL.Text, AlertType], [], []),
  'addAppliance' : IDL.Func([AddApplianceRequest], [ApplianceId], []),
  'addMaintenanceTask' : IDL.Func([AddMaintenanceTaskRequest], [TaskId], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeTask' : IDL.Func([IDL.Nat], [], []),
  'deleteAlert' : IDL.Func([IDL.Nat], [], []),
  'deleteAppliance' : IDL.Func([IDL.Nat], [], []),
  'deleteMaintenanceTask' : IDL.Func([IDL.Nat], [], []),
  'getActiveAlertsCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getAlertById' : IDL.Func([IDL.Nat], [Alert], ['query']),
  'getAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
  'getAlertsByDateRange' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(Alert)],
      ['query'],
    ),
  'getAlertsSortedBySeverity' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
  'getApplianceById' : IDL.Func([IDL.Nat], [Appliance], ['query']),
  'getApplianceSummary' : IDL.Func([], [ApplianceSummary], ['query']),
  'getAppliances' : IDL.Func([], [IDL.Vec(Appliance)], ['query']),
  'getAppliancesByCategory' : IDL.Func(
      [Category],
      [IDL.Vec(Appliance)],
      ['query'],
    ),
  'getAppliancesSortedByHealthScore' : IDL.Func(
      [],
      [IDL.Vec(Appliance)],
      ['query'],
    ),
  'getAppliancesSortedByName' : IDL.Func([], [IDL.Vec(Appliance)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCriticalAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getMaintenanceSummary' : IDL.Func([], [MaintenanceSummary], ['query']),
  'getMaintenanceTasks' : IDL.Func([], [IDL.Vec(MaintenanceTask)], ['query']),
  'getOverdueTasks' : IDL.Func([], [IDL.Vec(MaintenanceTask)], ['query']),
  'getPendingTasks' : IDL.Func([], [IDL.Vec(MaintenanceTask)], ['query']),
  'getSortedUpcomingTasks' : IDL.Func(
      [],
      [IDL.Vec(MaintenanceTask)],
      ['query'],
    ),
  'getTaskById' : IDL.Func([IDL.Nat], [MaintenanceTask], ['query']),
  'getTasksByPriority' : IDL.Func(
      [Priority],
      [IDL.Vec(MaintenanceTask)],
      ['query'],
    ),
  'getTasksByStatus' : IDL.Func(
      [Status],
      [IDL.Vec(MaintenanceTask)],
      ['query'],
    ),
  'getTasksForAppliance' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(MaintenanceTask)],
      ['query'],
    ),
  'getTasksWithDueDateBetweenRange' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(MaintenanceTask)],
      ['query'],
    ),
  'getUpcomingTasks' : IDL.Func([], [IDL.Vec(MaintenanceTask)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'insertTestData' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'resetUserData' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateAppliance' : IDL.Func([IDL.Nat, UpdateApplianceRequest], [], []),
  'updateApplianceHealthScores' : IDL.Func([], [], []),
  'updateMaintenanceTask' : IDL.Func(
      [IDL.Nat, UpdateMaintenanceTaskRequest],
      [],
      [],
    ),
  'updateTaskStatuses' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AlertType = IDL.Variant({
    'warning' : IDL.Null,
    'info' : IDL.Null,
    'critical' : IDL.Null,
  });
  const Category = IDL.Variant({
    'other' : IDL.Null,
    'hvac' : IDL.Null,
    'plumbing' : IDL.Null,
    'kitchen' : IDL.Null,
    'electrical' : IDL.Null,
    'laundry' : IDL.Null,
  });
  const AddApplianceRequest = IDL.Record({
    'name' : IDL.Text,
    'installDate' : IDL.Int,
    'lastServiceDate' : IDL.Int,
    'category' : Category,
    'brand' : IDL.Text,
  });
  const ApplianceId = IDL.Nat;
  const Status = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'overdue' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Priority = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'critical' : IDL.Null,
    'medium' : IDL.Null,
  });
  const AddMaintenanceTaskRequest = IDL.Record({
    'status' : Status,
    'title' : IDL.Text,
    'dueDate' : IDL.Int,
    'description' : IDL.Text,
    'priority' : Priority,
    'applianceId' : IDL.Opt(IDL.Nat),
  });
  const TaskId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Alert = IDL.Record({
    'id' : IDL.Nat,
    'alertType' : AlertType,
    'createdAt' : IDL.Int,
    'message' : IDL.Text,
  });
  const Appliance = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'installDate' : IDL.Int,
    'lastServiceDate' : IDL.Int,
    'category' : Category,
    'brand' : IDL.Text,
    'healthScore' : IDL.Int,
  });
  const ApplianceSummary = IDL.Record({
    'totalAppliances' : IDL.Nat,
    'oldestAppliance' : IDL.Opt(Appliance),
    'averageHealthScore' : IDL.Int,
    'mostServicedAppliance' : IDL.Opt(Appliance),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DashboardStats = IDL.Record({
    'homeHealthScore' : IDL.Int,
    'activeAlerts' : IDL.Nat,
    'upcomingTasks' : IDL.Nat,
  });
  const MaintenanceSummary = IDL.Record({
    'overdueTasks' : IDL.Nat,
    'totalTasks' : IDL.Nat,
    'completedTasks' : IDL.Nat,
    'upcomingTasks' : IDL.Nat,
  });
  const MaintenanceTask = IDL.Record({
    'id' : IDL.Nat,
    'status' : Status,
    'title' : IDL.Text,
    'dueDate' : IDL.Int,
    'description' : IDL.Text,
    'priority' : Priority,
    'applianceId' : IDL.Nat,
  });
  const UpdateApplianceRequest = IDL.Record({
    'name' : IDL.Text,
    'installDate' : IDL.Int,
    'lastServiceDate' : IDL.Int,
    'category' : Category,
    'brand' : IDL.Text,
  });
  const UpdateMaintenanceTaskRequest = IDL.Record({
    'status' : Status,
    'title' : IDL.Text,
    'dueDate' : IDL.Int,
    'description' : IDL.Text,
    'priority' : Priority,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAlert' : IDL.Func([IDL.Text, AlertType], [], []),
    'addAppliance' : IDL.Func([AddApplianceRequest], [ApplianceId], []),
    'addMaintenanceTask' : IDL.Func([AddMaintenanceTaskRequest], [TaskId], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeTask' : IDL.Func([IDL.Nat], [], []),
    'deleteAlert' : IDL.Func([IDL.Nat], [], []),
    'deleteAppliance' : IDL.Func([IDL.Nat], [], []),
    'deleteMaintenanceTask' : IDL.Func([IDL.Nat], [], []),
    'getActiveAlertsCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getAlertById' : IDL.Func([IDL.Nat], [Alert], ['query']),
    'getAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
    'getAlertsByDateRange' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(Alert)],
        ['query'],
      ),
    'getAlertsSortedBySeverity' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
    'getApplianceById' : IDL.Func([IDL.Nat], [Appliance], ['query']),
    'getApplianceSummary' : IDL.Func([], [ApplianceSummary], ['query']),
    'getAppliances' : IDL.Func([], [IDL.Vec(Appliance)], ['query']),
    'getAppliancesByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Appliance)],
        ['query'],
      ),
    'getAppliancesSortedByHealthScore' : IDL.Func(
        [],
        [IDL.Vec(Appliance)],
        ['query'],
      ),
    'getAppliancesSortedByName' : IDL.Func([], [IDL.Vec(Appliance)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCriticalAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getMaintenanceSummary' : IDL.Func([], [MaintenanceSummary], ['query']),
    'getMaintenanceTasks' : IDL.Func([], [IDL.Vec(MaintenanceTask)], ['query']),
    'getOverdueTasks' : IDL.Func([], [IDL.Vec(MaintenanceTask)], ['query']),
    'getPendingTasks' : IDL.Func([], [IDL.Vec(MaintenanceTask)], ['query']),
    'getSortedUpcomingTasks' : IDL.Func(
        [],
        [IDL.Vec(MaintenanceTask)],
        ['query'],
      ),
    'getTaskById' : IDL.Func([IDL.Nat], [MaintenanceTask], ['query']),
    'getTasksByPriority' : IDL.Func(
        [Priority],
        [IDL.Vec(MaintenanceTask)],
        ['query'],
      ),
    'getTasksByStatus' : IDL.Func(
        [Status],
        [IDL.Vec(MaintenanceTask)],
        ['query'],
      ),
    'getTasksForAppliance' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(MaintenanceTask)],
        ['query'],
      ),
    'getTasksWithDueDateBetweenRange' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(MaintenanceTask)],
        ['query'],
      ),
    'getUpcomingTasks' : IDL.Func([], [IDL.Vec(MaintenanceTask)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'insertTestData' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'resetUserData' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateAppliance' : IDL.Func([IDL.Nat, UpdateApplianceRequest], [], []),
    'updateApplianceHealthScores' : IDL.Func([], [], []),
    'updateMaintenanceTask' : IDL.Func(
        [IDL.Nat, UpdateMaintenanceTaskRequest],
        [],
        [],
      ),
    'updateTaskStatuses' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };