/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AddMaintenanceTaskRequest {
    status: Status;
    title: string;
    dueDate: bigint;
    description: string;
    priority: Priority;
    applianceId?: bigint;
}
export interface ApplianceSummary {
    totalAppliances: bigint;
    oldestAppliance?: Appliance;
    averageHealthScore: bigint;
    mostServicedAppliance?: Appliance;
}
export type ApplianceId = bigint;
export interface MaintenanceSummary {
    overdueTasks: bigint;
    totalTasks: bigint;
    completedTasks: bigint;
    upcomingTasks: bigint;
}
export interface UpdateMaintenanceTaskRequest {
    status: Status;
    title: string;
    dueDate: bigint;
    description: string;
    priority: Priority;
}
export interface DashboardStats {
    homeHealthScore: bigint;
    activeAlerts: bigint;
    upcomingTasks: bigint;
}
export interface MaintenanceTask {
    id: bigint;
    status: Status;
    title: string;
    dueDate: bigint;
    description: string;
    priority: Priority;
    applianceId: bigint;
}
export interface AddApplianceRequest {
    name: string;
    installDate: bigint;
    lastServiceDate: bigint;
    category: Category;
    brand: string;
}
export type TaskId = bigint;
export interface Appliance {
    id: bigint;
    name: string;
    installDate: bigint;
    lastServiceDate: bigint;
    category: Category;
    brand: string;
    healthScore: bigint;
}
export interface UpdateApplianceRequest {
    name: string;
    installDate: bigint;
    lastServiceDate: bigint;
    category: Category;
    brand: string;
}
export interface Alert {
    id: bigint;
    alertType: AlertType;
    createdAt: bigint;
    message: string;
}
export interface UserProfile {
    name: string;
}
export enum AlertType {
    warning = "warning",
    info = "info",
    critical = "critical"
}
export enum Category {
    other = "other",
    hvac = "hvac",
    plumbing = "plumbing",
    kitchen = "kitchen",
    electrical = "electrical",
    laundry = "laundry"
}
export enum Priority {
    low = "low",
    high = "high",
    critical = "critical",
    medium = "medium"
}
export enum Status {
    pending = "pending",
    completed = "completed",
    overdue = "overdue",
    inProgress = "inProgress"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAlert(message: string, alertType: AlertType): Promise<void>;
    addAppliance(request: AddApplianceRequest): Promise<ApplianceId>;
    addMaintenanceTask(request: AddMaintenanceTaskRequest): Promise<TaskId>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    completeTask(taskId: bigint): Promise<void>;
    deleteAlert(alertId: bigint): Promise<void>;
    deleteAppliance(applianceId: bigint): Promise<void>;
    deleteMaintenanceTask(taskId: bigint): Promise<void>;
    getActiveAlertsCount(): Promise<bigint>;
    getAlertById(alertId: bigint): Promise<Alert>;
    getAlerts(): Promise<Array<Alert>>;
    getAlertsByDateRange(startDate: bigint, endDate: bigint): Promise<Array<Alert>>;
    getAlertsSortedBySeverity(): Promise<Array<Alert>>;
    getApplianceById(applianceId: bigint): Promise<Appliance>;
    getApplianceSummary(): Promise<ApplianceSummary>;
    getAppliances(): Promise<Array<Appliance>>;
    getAppliancesByCategory(category: Category): Promise<Array<Appliance>>;
    getAppliancesSortedByHealthScore(): Promise<Array<Appliance>>;
    getAppliancesSortedByName(): Promise<Array<Appliance>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCriticalAlerts(): Promise<Array<Alert>>;
    getDashboardStats(): Promise<DashboardStats>;
    getMaintenanceSummary(): Promise<MaintenanceSummary>;
    getMaintenanceTasks(): Promise<Array<MaintenanceTask>>;
    getOverdueTasks(): Promise<Array<MaintenanceTask>>;
    getPendingTasks(): Promise<Array<MaintenanceTask>>;
    getSortedUpcomingTasks(): Promise<Array<MaintenanceTask>>;
    getTaskById(taskId: bigint): Promise<MaintenanceTask>;
    getTasksByPriority(priority: Priority): Promise<Array<MaintenanceTask>>;
    getTasksByStatus(status: Status): Promise<Array<MaintenanceTask>>;
    getTasksForAppliance(applianceId: bigint): Promise<Array<MaintenanceTask>>;
    getTasksWithDueDateBetweenRange(startDate: bigint, endDate: bigint): Promise<Array<MaintenanceTask>>;
    getUpcomingTasks(): Promise<Array<MaintenanceTask>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    insertTestData(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    resetUserData(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateAppliance(applianceId: bigint, request: UpdateApplianceRequest): Promise<void>;
    updateApplianceHealthScores(): Promise<void>;
    updateMaintenanceTask(taskId: bigint, request: UpdateMaintenanceTaskRequest): Promise<void>;
    updateTaskStatuses(): Promise<void>;
}
import type { AddApplianceRequest as _AddApplianceRequest, AddMaintenanceTaskRequest as _AddMaintenanceTaskRequest, Alert as _Alert, AlertType as _AlertType, Appliance as _Appliance, ApplianceSummary as _ApplianceSummary, Category as _Category, MaintenanceTask as _MaintenanceTask, Priority as _Priority, Status as _Status, UpdateApplianceRequest as _UpdateApplianceRequest, UpdateMaintenanceTaskRequest as _UpdateMaintenanceTaskRequest, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAlert(arg0: string, arg1: AlertType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAlert(arg0, to_candid_AlertType_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAlert(arg0, to_candid_AlertType_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async addAppliance(arg0: AddApplianceRequest): Promise<ApplianceId> {
        if (this.processError) {
            try {
                const result = await this.actor.addAppliance(to_candid_AddApplianceRequest_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAppliance(to_candid_AddApplianceRequest_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addMaintenanceTask(arg0: AddMaintenanceTaskRequest): Promise<TaskId> {
        if (this.processError) {
            try {
                const result = await this.actor.addMaintenanceTask(to_candid_AddMaintenanceTaskRequest_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMaintenanceTask(to_candid_AddMaintenanceTaskRequest_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async completeTask(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeTask(arg0);
            return result;
        }
    }
    async deleteAlert(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAlert(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAlert(arg0);
            return result;
        }
    }
    async deleteAppliance(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAppliance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAppliance(arg0);
            return result;
        }
    }
    async deleteMaintenanceTask(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMaintenanceTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMaintenanceTask(arg0);
            return result;
        }
    }
    async getActiveAlertsCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveAlertsCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveAlertsCount();
            return result;
        }
    }
    async getAlertById(arg0: bigint): Promise<Alert> {
        if (this.processError) {
            try {
                const result = await this.actor.getAlertById(arg0);
                return from_candid_Alert_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAlertById(arg0);
            return from_candid_Alert_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAlerts(): Promise<Array<Alert>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAlerts();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAlerts();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAlertsByDateRange(arg0: bigint, arg1: bigint): Promise<Array<Alert>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAlertsByDateRange(arg0, arg1);
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAlertsByDateRange(arg0, arg1);
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAlertsSortedBySeverity(): Promise<Array<Alert>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAlertsSortedBySeverity();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAlertsSortedBySeverity();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApplianceById(arg0: bigint): Promise<Appliance> {
        if (this.processError) {
            try {
                const result = await this.actor.getApplianceById(arg0);
                return from_candid_Appliance_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApplianceById(arg0);
            return from_candid_Appliance_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApplianceSummary(): Promise<ApplianceSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getApplianceSummary();
                return from_candid_ApplianceSummary_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApplianceSummary();
            return from_candid_ApplianceSummary_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAppliances(): Promise<Array<Appliance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppliances();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppliances();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAppliancesByCategory(arg0: Category): Promise<Array<Appliance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppliancesByCategory(to_candid_Category_n5(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppliancesByCategory(to_candid_Category_n5(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAppliancesSortedByHealthScore(): Promise<Array<Appliance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppliancesSortedByHealthScore();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppliancesSortedByHealthScore();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAppliancesSortedByName(): Promise<Array<Appliance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppliancesSortedByName();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppliancesSortedByName();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCriticalAlerts(): Promise<Array<Alert>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCriticalAlerts();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCriticalAlerts();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getMaintenanceSummary(): Promise<MaintenanceSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getMaintenanceSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMaintenanceSummary();
            return result;
        }
    }
    async getMaintenanceTasks(): Promise<Array<MaintenanceTask>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMaintenanceTasks();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMaintenanceTasks();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOverdueTasks(): Promise<Array<MaintenanceTask>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOverdueTasks();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOverdueTasks();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingTasks(): Promise<Array<MaintenanceTask>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingTasks();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingTasks();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSortedUpcomingTasks(): Promise<Array<MaintenanceTask>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSortedUpcomingTasks();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSortedUpcomingTasks();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTaskById(arg0: bigint): Promise<MaintenanceTask> {
        if (this.processError) {
            try {
                const result = await this.actor.getTaskById(arg0);
                return from_candid_MaintenanceTask_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTaskById(arg0);
            return from_candid_MaintenanceTask_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTasksByPriority(arg0: Priority): Promise<Array<MaintenanceTask>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasksByPriority(to_candid_Priority_n11(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasksByPriority(to_candid_Priority_n11(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTasksByStatus(arg0: Status): Promise<Array<MaintenanceTask>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasksByStatus(to_candid_Status_n9(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasksByStatus(to_candid_Status_n9(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTasksForAppliance(arg0: bigint): Promise<Array<MaintenanceTask>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasksForAppliance(arg0);
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasksForAppliance(arg0);
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTasksWithDueDateBetweenRange(arg0: bigint, arg1: bigint): Promise<Array<MaintenanceTask>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasksWithDueDateBetweenRange(arg0, arg1);
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasksWithDueDateBetweenRange(arg0, arg1);
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUpcomingTasks(): Promise<Array<MaintenanceTask>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUpcomingTasks();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUpcomingTasks();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async insertTestData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.insertTestData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.insertTestData();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async resetUserData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetUserData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetUserData();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateAppliance(arg0: bigint, arg1: UpdateApplianceRequest): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAppliance(arg0, to_candid_UpdateApplianceRequest_n38(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAppliance(arg0, to_candid_UpdateApplianceRequest_n38(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateApplianceHealthScores(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateApplianceHealthScores();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateApplianceHealthScores();
            return result;
        }
    }
    async updateMaintenanceTask(arg0: bigint, arg1: UpdateMaintenanceTaskRequest): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMaintenanceTask(arg0, to_candid_UpdateMaintenanceTaskRequest_n39(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMaintenanceTask(arg0, to_candid_UpdateMaintenanceTaskRequest_n39(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateTaskStatuses(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTaskStatuses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTaskStatuses();
            return result;
        }
    }
}
function from_candid_AlertType_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AlertType): AlertType {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Alert_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Alert): Alert {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_ApplianceSummary_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApplianceSummary): ApplianceSummary {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Appliance_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Appliance): Appliance {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Category_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_MaintenanceTask_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MaintenanceTask): MaintenanceTask {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_Priority_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Priority): Priority {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Appliance]): Appliance | null {
    return value.length === 0 ? null : from_candid_Appliance_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    alertType: _AlertType;
    createdAt: bigint;
    message: string;
}): {
    id: bigint;
    alertType: AlertType;
    createdAt: bigint;
    message: string;
} {
    return {
        id: value.id,
        alertType: from_candid_AlertType_n17(_uploadFile, _downloadFile, value.alertType),
        createdAt: value.createdAt,
        message: value.message
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    installDate: bigint;
    lastServiceDate: bigint;
    category: _Category;
    brand: string;
    healthScore: bigint;
}): {
    id: bigint;
    name: string;
    installDate: bigint;
    lastServiceDate: bigint;
    category: Category;
    brand: string;
    healthScore: bigint;
} {
    return {
        id: value.id,
        name: value.name,
        installDate: value.installDate,
        lastServiceDate: value.lastServiceDate,
        category: from_candid_Category_n22(_uploadFile, _downloadFile, value.category),
        brand: value.brand,
        healthScore: value.healthScore
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalAppliances: bigint;
    oldestAppliance: [] | [_Appliance];
    averageHealthScore: bigint;
    mostServicedAppliance: [] | [_Appliance];
}): {
    totalAppliances: bigint;
    oldestAppliance?: Appliance;
    averageHealthScore: bigint;
    mostServicedAppliance?: Appliance;
} {
    return {
        totalAppliances: value.totalAppliances,
        oldestAppliance: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.oldestAppliance)),
        averageHealthScore: value.averageHealthScore,
        mostServicedAppliance: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.mostServicedAppliance))
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _Status;
    title: string;
    dueDate: bigint;
    description: string;
    priority: _Priority;
    applianceId: bigint;
}): {
    id: bigint;
    status: Status;
    title: string;
    dueDate: bigint;
    description: string;
    priority: Priority;
    applianceId: bigint;
} {
    return {
        id: value.id,
        status: from_candid_Status_n34(_uploadFile, _downloadFile, value.status),
        title: value.title,
        dueDate: value.dueDate,
        description: value.description,
        priority: from_candid_Priority_n36(_uploadFile, _downloadFile, value.priority),
        applianceId: value.applianceId
    };
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    warning: null;
} | {
    info: null;
} | {
    critical: null;
}): AlertType {
    return "warning" in value ? AlertType.warning : "info" in value ? AlertType.info : "critical" in value ? AlertType.critical : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    hvac: null;
} | {
    plumbing: null;
} | {
    kitchen: null;
} | {
    electrical: null;
} | {
    laundry: null;
}): Category {
    return "other" in value ? Category.other : "hvac" in value ? Category.hvac : "plumbing" in value ? Category.plumbing : "kitchen" in value ? Category.kitchen : "electrical" in value ? Category.electrical : "laundry" in value ? Category.laundry : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    overdue: null;
} | {
    inProgress: null;
}): Status {
    return "pending" in value ? Status.pending : "completed" in value ? Status.completed : "overdue" in value ? Status.overdue : "inProgress" in value ? Status.inProgress : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    critical: null;
} | {
    medium: null;
}): Priority {
    return "low" in value ? Priority.low : "high" in value ? Priority.high : "critical" in value ? Priority.critical : "medium" in value ? Priority.medium : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Alert>): Array<Alert> {
    return value.map((x)=>from_candid_Alert_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Appliance>): Array<Appliance> {
    return value.map((x)=>from_candid_Appliance_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MaintenanceTask>): Array<MaintenanceTask> {
    return value.map((x)=>from_candid_MaintenanceTask_n32(_uploadFile, _downloadFile, x));
}
function to_candid_AddApplianceRequest_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AddApplianceRequest): _AddApplianceRequest {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_AddMaintenanceTaskRequest_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AddMaintenanceTaskRequest): _AddMaintenanceTaskRequest {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_AlertType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AlertType): _AlertType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Category_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_Priority_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Priority): _Priority {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_Status_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): _Status {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateApplianceRequest_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateApplianceRequest): _UpdateApplianceRequest {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateMaintenanceTaskRequest_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateMaintenanceTaskRequest): _UpdateMaintenanceTaskRequest {
    return to_candid_record_n40(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    installDate: bigint;
    lastServiceDate: bigint;
    category: Category;
    brand: string;
}): {
    name: string;
    installDate: bigint;
    lastServiceDate: bigint;
    category: _Category;
    brand: string;
} {
    return {
        name: value.name,
        installDate: value.installDate,
        lastServiceDate: value.lastServiceDate,
        category: to_candid_Category_n5(_uploadFile, _downloadFile, value.category),
        brand: value.brand
    };
}
function to_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: Status;
    title: string;
    dueDate: bigint;
    description: string;
    priority: Priority;
}): {
    status: _Status;
    title: string;
    dueDate: bigint;
    description: string;
    priority: _Priority;
} {
    return {
        status: to_candid_Status_n9(_uploadFile, _downloadFile, value.status),
        title: value.title,
        dueDate: value.dueDate,
        description: value.description,
        priority: to_candid_Priority_n11(_uploadFile, _downloadFile, value.priority)
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: Status;
    title: string;
    dueDate: bigint;
    description: string;
    priority: Priority;
    applianceId?: bigint;
}): {
    status: _Status;
    title: string;
    dueDate: bigint;
    description: string;
    priority: _Priority;
    applianceId: [] | [bigint];
} {
    return {
        status: to_candid_Status_n9(_uploadFile, _downloadFile, value.status),
        title: value.title,
        dueDate: value.dueDate,
        description: value.description,
        priority: to_candid_Priority_n11(_uploadFile, _downloadFile, value.priority),
        applianceId: value.applianceId ? candid_some(value.applianceId) : candid_none()
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): {
    pending: null;
} | {
    completed: null;
} | {
    overdue: null;
} | {
    inProgress: null;
} {
    return value == Status.pending ? {
        pending: null
    } : value == Status.completed ? {
        completed: null
    } : value == Status.overdue ? {
        overdue: null
    } : value == Status.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Priority): {
    low: null;
} | {
    high: null;
} | {
    critical: null;
} | {
    medium: null;
} {
    return value == Priority.low ? {
        low: null
    } : value == Priority.high ? {
        high: null
    } : value == Priority.critical ? {
        critical: null
    } : value == Priority.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AlertType): {
    warning: null;
} | {
    info: null;
} | {
    critical: null;
} {
    return value == AlertType.warning ? {
        warning: null
    } : value == AlertType.info ? {
        info: null
    } : value == AlertType.critical ? {
        critical: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    other: null;
} | {
    hvac: null;
} | {
    plumbing: null;
} | {
    kitchen: null;
} | {
    electrical: null;
} | {
    laundry: null;
} {
    return value == Category.other ? {
        other: null
    } : value == Category.hvac ? {
        hvac: null
    } : value == Category.plumbing ? {
        plumbing: null
    } : value == Category.kitchen ? {
        kitchen: null
    } : value == Category.electrical ? {
        electrical: null
    } : value == Category.laundry ? {
        laundry: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
